pipeline {
  agent any
  tools {
    jdk 'JDK 17'
    maven 'Maven 3.9'
  }
  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Build') {
      steps { bat 'mvn clean compile' }
    }

    stage('Unit Test') {
      steps { bat 'mvn test' }
      post {
        always {
          junit 'target/surefire-reports/*.xml'
        }
      }
    }

    stage('Package') {
      steps { bat 'mvn package -DskipTests' }
      post {
        success {
          archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
        }
      }
    }
  }
  post {
    success { echo 'Java CI pipeline completed successfully!' }
    failure { echo 'Java CI pipeline failed. Check logs.' }
  }
}
